use super::{Bindings, CommandId};

impl Bindings {
    pub fn lookup_name(name: &str) -> Option<CommandId> {
        match name {
            "forward-char" | "forward-character" => Some(CommandId::ForwardChar),
            "backward-char" | "backward-character" => Some(CommandId::BackwardChar),
            "forward-line" | "next-line" => Some(CommandId::ForwardLine),
            "backward-line" | "previous-line" => Some(CommandId::BackwardLine),
            "goto-bol" | "beginning-of-line" => Some(CommandId::GotoBol),
            "goto-eol" | "end-of-line" => Some(CommandId::GotoEol),
            "goto-bob" | "beginning-of-file" => Some(CommandId::GotoBob),
            "goto-eob" | "end-of-file" => Some(CommandId::GotoEob),
            "goto-line" => Some(CommandId::GotoLine),
            "forward-page" | "next-page" => Some(CommandId::ForwardPage),
            "backward-page" | "previous-page" => Some(CommandId::BackwardPage),
            "set-mark" => Some(CommandId::SetMark),
            "swap-mark" | "exchange-point-and-mark" => Some(CommandId::SwapMark),
            "kill-line" => Some(CommandId::KillLine),
            "kill-text" | "kill-to-end-of-line" => Some(CommandId::KillText),
            "kill-region" => Some(CommandId::KillRegion),
            "yank" => Some(CommandId::Yank),
            "copy-region" => Some(CommandId::CopyRegion),
            "lower-region" | "case-region-lower" => Some(CommandId::LowerRegion),
            "upper-region" | "case-region-upper" => Some(CommandId::UpperRegion),
            "forward-word" | "next-word" => Some(CommandId::ForwardWord),
            "backward-word" | "previous-word" => Some(CommandId::BackwardWord),
            "upper-word" | "case-word-upper" => Some(CommandId::UpperWord),
            "lower-word" | "case-word-lower" => Some(CommandId::LowerWord),
            "cap-word" | "case-word-capitalize" => Some(CommandId::CapWord),
            "delete-forward-word" | "delete-next-word" => Some(CommandId::DeleteForwardWord),
            "delete-backward-word" | "delete-previous-word" => Some(CommandId::DeleteBackwardWord),
            "open-line" => Some(CommandId::OpenLine),
            "insert-newline" | "newline" => Some(CommandId::InsertNewline),
            "insert-tab" | "handle-tab" => Some(CommandId::InsertTab),
            "forward-delete" | "delete-next-character" => Some(CommandId::ForwardDelete),
            "backward-delete" | "delete-previous-character" => Some(CommandId::BackwardDelete),
            "forward-search" | "search-forward" => Some(CommandId::ForwardSearch),
            "backward-search" | "search-reverse" => Some(CommandId::BackwardSearch),
            "isearch-forward" | "incremental-search" => Some(CommandId::IsearchForward),
            "isearch-backward" | "reverse-incremental-search" => Some(CommandId::IsearchBackward),
            "query-replace" | "query-replace-string" => Some(CommandId::QueryReplace),
            "refresh-screen" | "clear-and-redraw" => Some(CommandId::RefreshScreen),
            "suspend-emacs" => Some(CommandId::SuspendEmacs),
            "undo" => Some(CommandId::Undo),
            "execute-extended-command" | "execute-named-command" => Some(CommandId::ExecuteCommand),
            "quit-emacs" | "exit-emacs" => Some(CommandId::QuitEmacs),
            "keyboard-quit" | "abort-command" => Some(CommandId::KeyboardQuit),
            "start-kbd-macro" | "begin-macro" => Some(CommandId::StartKbdMacro),
            "end-kbd-macro" | "end-macro" => Some(CommandId::EndKbdMacro),
            "call-last-kbd-macro" | "execute-macro" => Some(CommandId::CallKbdMacro),
            "set-variable" | "set" => Some(CommandId::SetVar),
            "save-file" => Some(CommandId::SaveFile),
            "find-file" => Some(CommandId::FindFile),
            "write-file" => Some(CommandId::WriteFile),
            "delete-window" => Some(CommandId::DeleteWindow),
            "one-window" | "delete-other-windows" => Some(CommandId::OneWindow),
            "split-window" | "split-current-window" => Some(CommandId::SplitWindowDown),
            "other-window" => Some(CommandId::OtherWindow),
            "switch-buffer" | "select-buffer" => Some(CommandId::SwitchBuffer),
            "kill-buffer" | "delete-buffer" => Some(CommandId::KillBuffer),
            "toggle-magic" => Some(CommandId::ToggleMagic),
            "fill-paragraph" => Some(CommandId::FillPara),
            "justify-paragraph" => Some(CommandId::JustifyPara),

            "set-fill-column" => Some(CommandId::SetFillColumn),
            "delete-blank-lines" => Some(CommandId::DeleteBlankLines),
            "quote-char" | "quote-character" => Some(CommandId::QuoteChar),
            "transpose-characters" => Some(CommandId::TransposeChars),
            "count-words" => Some(CommandId::CountWords),
            "clear-message-line" => Some(CommandId::ClearMessageLine),
            "list-buffers" => Some(CommandId::ListBuffers),
            "trim-line" => Some(CommandId::TrimLine),
            "detab-line" => Some(CommandId::DetabLine),
            "entab-line" => Some(CommandId::EntabLine),
            "nop" => Some(CommandId::Nop),
            "buffer-position" => Some(CommandId::BufferPosition),
            "describe-key" => Some(CommandId::DescribeKey),
            "describe-bindings" => Some(CommandId::DescribeBindings),
            "apropos" => Some(CommandId::Apropos),
            "next-window" => Some(CommandId::NextWindow),
            "previous-window" => Some(CommandId::PreviousWindow),
            "grow-window" => Some(CommandId::GrowWindow),
            "shrink-window" => Some(CommandId::ShrinkWindow),
            "resize-window" => Some(CommandId::ResizeWindow),
            "read-file" => Some(CommandId::ReadFile),
            "insert-file" => Some(CommandId::InsertFile),
            "view-file" => Some(CommandId::ViewFile),
            "overwrite-string" => Some(CommandId::OverwriteString),
            "insert-string" => Some(CommandId::InsertString),
            "goto-matching-fence" => Some(CommandId::GotoMatchingFence),
            _ => Self::lookup_name_ext(name),
        }
    }

    fn lookup_name_ext(name: &str) -> Option<CommandId> {
        match name {
            "replace-string" => Some(CommandId::ReplaceString),
            "add-mode" => Some(CommandId::AddMode),
            "delete-mode" => Some(CommandId::DeleteMode),
            "add-global-mode" => Some(CommandId::AddGlobalMode),
            "delete-global-mode" => Some(CommandId::DeleteGlobalMode),
            "write-message" => Some(CommandId::WriteMessage),
            "name-buffer" => Some(CommandId::NameBuffer),
            "change-file-name" => Some(CommandId::ChangeFileName),
            "unmark-buffer" => Some(CommandId::UnmarkBuffer),
            "unbind-key" => Some(CommandId::UnbindKey),
            "bind-to-key" => Some(CommandId::BindToKey),
            "quick-exit" => Some(CommandId::QuickExit),
            "move-window-down" => Some(CommandId::MoveWindowDown),
            "move-window-up" => Some(CommandId::MoveWindowUp),
            "scroll-next-up" => Some(CommandId::ScrollNextUp),
            "scroll-next-down" => Some(CommandId::ScrollNextDown),
            "hunt-forward" => Some(CommandId::HuntForward),
            "hunt-backward" => Some(CommandId::HuntBackward),
            "next-buffer" => Some(CommandId::NextBuffer),
            "insert-space" => Some(CommandId::InsertSpace),
            "newline-and-indent" => Some(CommandId::NewlineAndIndent),
            "wrap-word" => Some(CommandId::WrapWord),
            "redraw-display" => Some(CommandId::RedrawDisplay),
            "update-screen" => Some(CommandId::UpdateScreen),
            "change-screen-size" => Some(CommandId::ChangeScreenSize),
            "change-screen-width" => Some(CommandId::ChangeScreenWidth),
            "save-window" => Some(CommandId::SaveWindow),
            "restore-window" => Some(CommandId::RestoreWindow),
            "help" => Some(CommandId::Help),
            "store-macro" => Some(CommandId::StoreMacro),
            cmd if let Some(n) = cmd.strip_prefix("execute-macro-") => {
                let n: u8 = n.parse().ok()?;
                Some(CommandId::ExecuteMacro(n))
            }
            "execute-buffer" => Some(CommandId::ExecuteBuffer),
            "execute-command-line" => Some(CommandId::ExecuteCommandLine),
            "execute-file" => Some(CommandId::ExecuteFile),
            "execute-program" => Some(CommandId::ExecuteProgram),
            "shell-command" => Some(CommandId::ShellCommand),
            "filter-buffer" => Some(CommandId::FilterBuffer),
            "pipe-command" => Some(CommandId::PipeCommand),
            "i-shell" => Some(CommandId::IShell),
            "store-procedure" => Some(CommandId::StoreProcedure),
            "execute-procedure" | "run" => Some(CommandId::ExecuteProcedure),
            "kill-paragraph" => Some(CommandId::KillParagraph),
            "goto-bop" | "previous-paragraph" => Some(CommandId::GotoBop),
            "goto-eop" | "next-paragraph" => Some(CommandId::GotoEop),
            "universal-argument" => Some(CommandId::UniversalArgument),
            "meta-prefix" => Some(CommandId::MetaPrefix),
            "ctrl-x-prefix" | "ctlx-prefix" => Some(CommandId::CtrlXPrefix),
            _ => None,
        }
    }
}
